CREATE TABLE STYDENTS (
  Id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO STYDENTS VALUES (0001, 'Alexey', 15, 'Surgut');
INSERT INTO STYDENTS VALUES (0002, 'Vlad', 19, 'Kazan');
INSERT INTO STYDENTS VALUES (0003, 'Yana', 16, 'Tyumen');
INSERT INTO STYDENTS VALUES (0004, 'Boris', 20, 'Anapa');
INSERT INTO STYDENTS VALUES (0005, 'Irina', 18, 'Volgograd');

-- fetch 
SELECT * FROM STYDENTS;